# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

import time


def sum_of_even_valued_fibonacci(max_number: int):
    current_number = 1
    next_number = 2
    result = 0

    while next_number < max_number:
        if next_number % 2 == 0:
            result += next_number

        last_number = current_number
        current_number = next_number
        next_number = last_number + current_number

    return result


def main():
    start = time.time()

    print('result:', sum_of_even_valued_fibonacci(4000000))

    end = time.time()
    print('Milliseconds: ' + str((end - start) * 1000))


main()
