# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle	 	Tn = n(n + 1) / 2	 	1, 3, 6, 10, 15, ...
# Pentagonal    Pn = n(3n − 1) / 2	    1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn = n(2n − 1)	 	    1, 6, 15, 28, 45, ...

# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

import time
from common_functions import is_pentagonal, is_triangle, is_hexagonal


def find_triangular_pentagonal_and_hexagonal(start_hex_index: int) -> int:
    i = start_hex_index

    while True:
        num = i * (2 * i - 1)   # get next hexagonal

        if is_hexagonal(num) and is_pentagonal(num) and is_triangle(num):
            return num
        i += 1


def main():
    start = time.time()

    start_hex_index = 144
    print('result:', find_triangular_pentagonal_and_hexagonal(start_hex_index))

    end = time.time()
    print('Seconds: ' + str(end - start))


if __name__ == '__main__':
    main()
else:
    print('__name__ is', __name__)
