# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle	 	Tn = n(n + 1) / 2	 	1, 3, 6, 10, 15, ...
# Pentagonal    Pn = n(3n − 1) / 2	    1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn = n(2n − 1)	 	    1, 6, 15, 28, 45, ...

# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

import time


def is_pentagonal(num: int) -> bool:
    p = (((24 * num + 1) ** 0.5) + 1) / 6
    return p.is_integer()


def is_triangle(num: int) -> bool:
    t = (((8 * num + 1) ** 0.5) - 1) / 2
    return t.is_integer()


def is_hexagonal(num: int) -> bool:
    h = (((8 * num + 1) ** 0.5) + 1) / 4
    return h.is_integer()


def get_next_hexagonal(num: int) -> int:
    return num * (2 * num - 1)


def solution() -> int:
    i = 144

    while True:
        num = get_next_hexagonal(i)

        if is_hexagonal(num) and is_pentagonal(num) and is_triangle(num):
            return num
        i += 1


def main():
    start = time.time()

    print('result:', solution())

    end = time.time()
    print('Seconds: ' + str(end - start))


if __name__ == '__main__':
    main()
else:
    print('__name__ is', __name__)
